/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explorador;

import modelo.Directorio;
import modelo.Elemento;
import modelo.Archivo;
import modelo.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import navegador.InterfazNavegador;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import papelera.InterfazPapelera;

/**
 *
 * @author Pc
 */
public class InterfazExplorador extends javax.swing.JFrame implements MouseListener, ActionListener {

    private final static Color COLOR_ENTRADA = new Color(46, 132, 175);
    private final static Color COLOR_SALIDA = new Color(46, 54, 68);
    private static JPanel[] opcionesSideBar = new JPanel[2];
    public static JPanel ultimoClickeado;

    public InterfazExplorador() {
        //Explorador Expl = new Explorador();
        initComponents();
        pintar();
        pintar_arbol();
        Direccion.setText(Explorador.Direccion);
        ImageIcon img_carpeta = new ImageIcon(getClass().getResource("/Imagenes/folder.png"));
        this.usuario.setText(Explorador.currentUser.getAttribute("nombre") + ": ");
        this.setVisible(true);
        jMenuItem6.setEnabled(Explorador.estadoPegar);
        opcionesSideBar[0] = navegador1;
        opcionesSideBar[1] = papelera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanelMenu = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Direccion = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        TextoBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelContenido = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        navegador1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        carpetas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        papelera = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();

        jMenuItem1.setText("Nuevo Directorio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Nuevo Archivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);
        jPopupMenu1.add(jSeparator2);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);
        jPopupMenu1.add(jSeparator3);

        jMenuItem4.setText("Copiar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setText("Cortar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setText("Pegar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setText("Editar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Explorador de Archivos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Shutdown_25px.png"))); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.setMinimumSize(new java.awt.Dimension(30, 30));
        cerrarSesion.setPreferredSize(new java.awt.Dimension(20, 20));
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Direccion.setText(" ");
        Direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Direccion.setOpaque(true);

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Back_25px_1.png"))); // NOI18N
        atras.setText("Carpeta Superior");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Edit_25px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_25px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Add_File_25px_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Add_Folder_25px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atras)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(65, 65, 65)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atras)
                        .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mi PC");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("sports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("food");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(854, 400));

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenido.setComponentPopupMenu(jPopupMenu1);
        jPanelContenido.setLayout(new java.awt.GridLayout(0, 8));
        jScrollPane2.setViewportView(jPanelContenido);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 68));

        navegador1.setBackground(new java.awt.Color(45, 52, 66));
        navegador1.setMinimumSize(new java.awt.Dimension(70, 70));
        navegador1.setPreferredSize(new java.awt.Dimension(70, 70));
        navegador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navegador1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navegador1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navegador1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cromo.png"))); // NOI18N

        javax.swing.GroupLayout navegador1Layout = new javax.swing.GroupLayout(navegador1);
        navegador1.setLayout(navegador1Layout);
        navegador1Layout.setHorizontalGroup(
            navegador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navegador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        navegador1Layout.setVerticalGroup(
            navegador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        carpetas.setBackground(new java.awt.Color(46, 132, 175));
        carpetas.setMinimumSize(new java.awt.Dimension(65, 65));
        carpetas.setPreferredSize(new java.awt.Dimension(70, 70));
        carpetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carpetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carpetasMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(68, 73, 81));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N

        javax.swing.GroupLayout carpetasLayout = new javax.swing.GroupLayout(carpetas);
        carpetas.setLayout(carpetasLayout);
        carpetasLayout.setHorizontalGroup(
            carpetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carpetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        carpetasLayout.setVerticalGroup(
            carpetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carpetasLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        papelera.setBackground(new java.awt.Color(45, 52, 66));
        papelera.setMinimumSize(new java.awt.Dimension(70, 70));
        papelera.setPreferredSize(new java.awt.Dimension(70, 70));
        papelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papeleraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papeleraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                papeleraMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N

        javax.swing.GroupLayout papeleraLayout = new javax.swing.GroupLayout(papelera);
        papelera.setLayout(papeleraLayout);
        papeleraLayout.setHorizontalGroup(
            papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(papeleraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        papeleraLayout.setVerticalGroup(
            papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        rSLabelHora1.setForeground(new java.awt.Color(45, 52, 66));
        rSLabelHora1.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(navegador1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(papelera, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navegador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(papelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1MouseClicked

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        Usuario.cerrarSesion();
        this.dispose();
        new InterfazInicio();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!TextoBuscar.getText().isEmpty()) {
            //this.dispose();
            new InterfazBusqueda(TextoBuscar.getText());
            TextoBuscar.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        if (Explorador.getCurrentLevel() > 1) {
            Explorador.currentDir = (Element) Explorador.currentDir.getParentNode();
            this.dispose();
            reducirDireccion();
            new InterfazExplorador();
            Explorador.setCurrentLevel(Explorador.getCurrentLevel() - 1);
        }
    }//GEN-LAST:event_atrasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new InterfazCrearElemento("Directorio");
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new InterfazCrearElemento("Archivo");
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //Boton Eliminar
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            JLabel nombreElemento = (JLabel) ultimoClickeado.getComponent(2);
            JLabel tipoElemento = (JLabel) ultimoClickeado.getComponent(1);
            if (tipoElemento.getText().equals("archivo")) {
                Element removido = Archivo.obtenerNodoHijo(nombreElemento.getText());
                if (removido.getAttribute("escritura").equals("Público") || removido.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                    Archivo a = new Archivo(Integer.parseInt(removido.getAttribute("id")), removido.getAttribute("nombre"), removido.getNodeName(), "Lorem", true, true, removido.getAttribute("dueño"), removido.getAttribute("texto"));
                    a.setEliminado("SI");
                    a.editar(ultimoClickeado);
                    jMenuItem6.setEnabled(false);
                    //pegar.setEnabled(false);
                    Explorador.estadoPegar = false;
                    ultimoClickeado = null;
                    this.dispose();
                    new InterfazExplorador();
                } else {
                    JOptionPane.showMessageDialog(null, "No tienes permisos para eliminar este elemento", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Element removido = Directorio.obtenerNodoHijo(nombreElemento.getText());
                if (removido.getAttribute("escritura").equals("Público") || removido.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                    Directorio d = new Directorio(Integer.parseInt(removido.getAttribute("id")), removido.getAttribute("nombre"), removido.getNodeName(), true, true, removido.getAttribute("dueño"));
                    d.setEliminado("SI");
                    d.editar(ultimoClickeado);
                    jMenuItem6.setEnabled(false);
                    //pegar.setEnabled(false);
                    Explorador.estadoPegar = false;
                    ultimoClickeado = null;
                    this.dispose();
                    new InterfazExplorador();
                } else {
                    JOptionPane.showMessageDialog(null, "No tienes permisos para eliminar este elemento", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //Boton Copiar
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            JLabel nombreElemento = (JLabel) ultimoClickeado.getComponent(2);
            JLabel tipoElemento = (JLabel) ultimoClickeado.getComponent(1);
            if (tipoElemento.getText().equals("archivo")) {
                Explorador.elementoaPegar = Archivo.obtenerNodoHijo(nombreElemento.getText());
            } else {
                Explorador.elementoaPegar = Directorio.obtenerNodoHijo(nombreElemento.getText());
            }
            if (Explorador.elementoaPegar.getAttribute("escritura").equals("Público") || Explorador.elementoaPegar.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                jMenuItem6.setEnabled(true);
                //pegar.setEnabled(true);
                Explorador.estadoPegar = true;
            } else {
                JOptionPane.showMessageDialog(null, "No tienes permisos para copiar este elemento", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //Boton Cortar
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            JLabel nombreElemento = (JLabel) ultimoClickeado.getComponent(2);
            JLabel tipoElemento = (JLabel) ultimoClickeado.getComponent(1);
            if (tipoElemento.getText().equals("archivo")) {
                Explorador.elementoaPegar = Archivo.obtenerNodoHijo(nombreElemento.getText());
            } else {
                Explorador.elementoaPegar = Directorio.obtenerNodoHijo(nombreElemento.getText());
            }
            if (Explorador.elementoaPegar.getAttribute("escritura").equals("Público") || Explorador.elementoaPegar.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                int id_removido = Integer.parseInt(Explorador.elementoaPegar.getAttribute("id"));
                Elemento removido = new Elemento(id_removido, nombreElemento.getText(), tipoElemento.getText(), "NO");
                removido.eliminar();
                jMenuItem6.setEnabled(true);
                //pegar.setEnabled(true);
                Explorador.estadoPegar = true;
            } else {
                JOptionPane.showMessageDialog(null, "No tienes permisos para cortar este elemento", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //Boton Pegar
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            if (Explorador.elementoaPegar.getNodeName().equals("archivo")) {
                Archivo archivo = new Archivo(Explorador.getCurrentId(), Explorador.elementoaPegar.getAttribute("nombre"), "Archivo", "Lorem", true, true, "adm", Explorador.elementoaPegar.getAttribute("texto"));
                if (Archivo.obtenerNodoHijo(Explorador.elementoaPegar.getAttribute("nombre")) == null) {
                    archivo.clonar();
                    this.dispose();
                    new InterfazExplorador();
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un archivo con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Directorio directorio = new Directorio(Explorador.getCurrentId(), Explorador.elementoaPegar.getAttribute("nombre"), "directorio", true, true, "Adm");
                if (Directorio.obtenerNodoHijo(Explorador.elementoaPegar.getAttribute("nombre")) == null) {
                    directorio.clonar();
                    this.dispose();
                    new InterfazExplorador();
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un directorio con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    //Boton editar
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        try {
            JLabel nombreDirectorio = (JLabel) ultimoClickeado.getComponent(2);
            JLabel tipoElemento = (JLabel) ultimoClickeado.getComponent(1);
            Element ultimo;
            if (tipoElemento.getText().equals("directorio")) {
                ultimo = Directorio.obtenerNodoHijo(nombreDirectorio.getText());
            } else {
                ultimo = Archivo.obtenerNodoHijo(nombreDirectorio.getText());
            }
            if (ultimo.getAttribute("escritura").equals("Público") && ultimo.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                this.dispose();
                if (tipoElemento.getText().equals("directorio")) {
                    new InterfazEditarDirectorio(nombreDirectorio.getText());
                } else {
                    new InterfazEditarArchivo(nombreDirectorio.getText(), ultimo.getAttribute("texto"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "No tienes permisos para editar este elemento", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jMenuItem7ActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jMenuItem3ActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jMenuItem2ActionPerformed(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.jMenuItem1ActionPerformed(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void carpetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpetasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_carpetasMouseEntered

    private void carpetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpetasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_carpetasMouseExited

    private void navegador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navegador1MouseEntered
        setColor(0);
    }//GEN-LAST:event_navegador1MouseEntered

    private void navegador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navegador1MouseExited
        exitColor(0);
    }//GEN-LAST:event_navegador1MouseExited

    private void papeleraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papeleraMouseEntered
        setColor(1);
    }//GEN-LAST:event_papeleraMouseEntered

    private void papeleraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papeleraMouseExited
        exitColor(1);
    }//GEN-LAST:event_papeleraMouseExited

    private void navegador1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navegador1MousePressed
        this.dispose();
        new InterfazNavegador();
    }//GEN-LAST:event_navegador1MousePressed

    private void papeleraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papeleraMousePressed
        this.dispose();
        new InterfazPapelera();
    }//GEN-LAST:event_papeleraMousePressed

    public void aumentarDireccion() {
        Explorador.Direccion = (Explorador.Direccion + "\\" + Explorador.currentDir.getAttributes().getNamedItem("nombre").getTextContent());
        System.out.println(Explorador.Direccion);
    }

    public void reducirDireccion() {
        int finalOccurrence = Explorador.Direccion.lastIndexOf("\\");
        Explorador.Direccion = (Explorador.Direccion.substring(0, finalOccurrence));
        System.out.println(Explorador.Direccion);
    }

    public void pintar() {
        NodeList listaNodos = Explorador.currentDir.getChildNodes();

        for (int i = 0; i < listaNodos.getLength(); i++) {
            if (listaNodos.item(i).getAttributes().getNamedItem("Eliminado").getTextContent().equals("NO")) {
                Panel panel = new Panel(listaNodos.item(i).getNodeName(), listaNodos.item(i).getAttributes().getNamedItem("nombre").getTextContent());
                JPanel elemento = panel.crear();
                elemento.addMouseListener(this);
                elemento.setComponentPopupMenu(jPopupMenu1);
                jPanelContenido.add(elemento);
            }
        }
    }

    public void pintar_arbol() {
        //javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mi PC");
        javax.swing.tree.DefaultMutableTreeNode hijo;
        Node raiz = Explorador.arbol.getDocumentElement();
        hijo = pintar_arbol_recursivo(raiz, "Mi PC");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(hijo));
    }

    public javax.swing.tree.DefaultMutableTreeNode pintar_arbol_recursivo(Node raiz, String nombreraiz) {
        javax.swing.tree.DefaultMutableTreeNode padre = new javax.swing.tree.DefaultMutableTreeNode(nombreraiz);
        javax.swing.tree.DefaultMutableTreeNode hijo;
        NodeList listaNodos = raiz.getChildNodes();
        for (int i = 0; i < listaNodos.getLength(); i++) {
            if (listaNodos.item(i).getNodeName().equals("directorio") && listaNodos.item(i).getAttributes().getNamedItem("Eliminado").getTextContent().equals("NO")) {
                hijo = pintar_arbol_recursivo(listaNodos.item(i), listaNodos.item(i).getAttributes().getNamedItem("nombre").getTextContent());
                padre.add(hijo);
            } else if(listaNodos.item(i).getAttributes().getNamedItem("Eliminado").getTextContent().equals("NO")) {
                hijo = new javax.swing.tree.DefaultMutableTreeNode(listaNodos.item(i).getAttributes().getNamedItem("nombre").getTextContent());
                padre.add(hijo);
            }
        }
        return padre;

    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    class Panel {

        private final String tipo, nombre;

        public Panel(String tipo, String nombre) {
            this.tipo = tipo;
            this.nombre = nombre;
        }

        public JPanel crear() {
            JPanel panel = new JPanel();
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            JLabel nombre = new JLabel(this.nombre);
            nombre.setAlignmentX(Component.CENTER_ALIGNMENT);
            JLabel tipo = new JLabel(this.tipo);
            tipo.setAlignmentX(Component.CENTER_ALIGNMENT);
            JLabel imagen = new JLabel("");
            imagen.setAlignmentX(Component.CENTER_ALIGNMENT);
            imagen.setSize(60, 60);
            if (this.tipo.equals("directorio")) {
                ImageIcon img_directorio = new ImageIcon(getClass().getResource("/Imagenes/folder.png"));
                ImageIcon img = new ImageIcon(img_directorio.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT));
                imagen.setIcon(img);
            }
            if (this.tipo.equals("archivo")) {
                ImageIcon img_archivo = new ImageIcon(getClass().getResource("/Imagenes/document.png"));
                ImageIcon img = new ImageIcon(img_archivo.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT));
                imagen.setIcon(img);
            }
            panel.add(imagen);
            panel.add(tipo);
            panel.add(nombre);
            panel.setBackground(Color.WHITE);
            return panel;
        }
    }

    @Override
    public void mouseClicked(MouseEvent me) {

        if (ultimoClickeado != null) {
            ultimoClickeado.setBackground(Color.WHITE);
        }
        me.getComponent().setBackground(new Color(187, 211, 249));
        ultimoClickeado = (JPanel) me.getComponent();
        JLabel tipoComponente = (JLabel) ultimoClickeado.getComponent(1);

        //Doble click = abrir
        if (me.getClickCount() == 2 && tipoComponente.getText().equals("directorio")) {
            JLabel nombreDirectorio = (JLabel) ultimoClickeado.getComponent(2);
            Element ultimo = Directorio.obtenerNodoHijo(nombreDirectorio.getText());

            if (ultimo.getAttribute("lectura").equals("Público") && ultimo.getAttribute("dueño").equals(Explorador.currentUser.getAttribute("nombre"))) {
                Explorador.currentDir = Directorio.obtenerNodoHijo(nombreDirectorio.getText());
                this.dispose();
                aumentarDireccion();
                new InterfazExplorador();
                Explorador.setCurrentLevel(Explorador.getCurrentLevel() + 1);
            } else {
                JOptionPane.showMessageDialog(null, "No tienes permisos de lectura de este fichero", "Error de acceso", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public static void setColor(int opcion) {
        opcionesSideBar[opcion].setBackground(COLOR_ENTRADA);
    }

    public static void exitColor(int opcion) {
        opcionesSideBar[opcion].setBackground(COLOR_SALIDA);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JTextField TextoBuscar;
    private javax.swing.JButton atras;
    private javax.swing.JPanel carpetas;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel navegador1;
    private javax.swing.JPanel papelera;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
